H=1E3;var qp_a,qp_b=5,qp_c=3,qp_d=qp_c,qp_e=0,qp_f=!1,qp_g=300,qp_h,qp_i,qp_j=-1E3,qp_k,qp_l=[],qp_m,qp_n=!1,qp_o,qp_p=!1,qp_q,qp_r;
function loadResource(){SCREEN_SHOW_ALL=!0;var a=new ProgressBar(0.8*W,40);a.regX=a.w/2;a.regY=a.h/2;a.x=W/2;a.y=H/2;stage.addChild(a);queue=new createjs.LoadQueue(!1);queue.setMaxConnections(30);loadGameData();loadFollowRes();queue.on("complete",onLoadComplete,null,!0);USE_NATIVE_SOUND||(IS_NATIVE_ANDROID?(createjs.Sound.registMySound("coin",0),createjs.Sound.registMySound("count",2),createjs.Sound.registMySound("silenttail",4),queue.loadFile({id:"sound",src:RES_DIR+"audio/all.mp3"})):(createjs.Sound.alternateExtensions=
["ogg"],queue.installPlugin(createjs.Sound),queue.loadManifest({path:RES_DIR+"audio/",manifest:[{src:"coin.mp3",id:"coin"},{src:"count.mp3",id:"count"}]},!1)));queue.loadManifest({path:RES_DIR+"img/",manifest:[{src:"bt_collect.png",id:"btCollect"},{src:"share.png",id:"share"},{src:"m0.png",id:"m0"},{src:"mb0.png",id:"mb0"},{src:"top.png",id:"top"},{src:"m1.png",id:"m1"},{src:"mb1.png",id:"mb1"},{src:"m2.png",id:"m2"},{src:"mb2.png",id:"mb2"},{src:"m3.png",id:"m3"},{src:"mb3.png",id:"mb3"},{src:"d0.png",
id:"d0"},{src:"d1.png",id:"d1"},{src:"d2.png",id:"d2"},{src:"d3.png",id:"d3"},{src:"bt1.png",id:"bt1"},{src:"bt2.png",id:"bt2"},{src:"bt3.png",id:"bt3"},{src:"close.png",id:"close"},{src:"bucket0.png",id:"bucket0"},{src:"bucket1.png",id:"bucket1"},{src:"bucket2.png",id:"bucket2"},{src:"bucket3.png",id:"bucket3"},{src:"bucket4.png",id:"bucket4"},{src:"bucket5.png",id:"bucket5"},{src:"coin.png",id:"coin"},{src:"bar.png",id:"bar"},{src:"p01.png",id:"p01"},{src:"p02.png",id:"p02"},{src:"p03.png",id:"p03"},
{src:"p04.png",id:"p04"},{src:"p05.png",id:"p05"},{src:"p06.png",id:"p06"},{src:"p07.png",id:"p07"},{src:"p08.png",id:"p08"},{src:"p11.png",id:"p11"},{src:"p12.png",id:"p12"},{src:"p13.png",id:"p13"},{src:"p14.png",id:"p14"},{src:"p15.png",id:"p15"},{src:"p16.png",id:"p16"},{src:"p17.png",id:"p17"},{src:"p18.png",id:"p18"},{src:"p21.png",id:"p21"},{src:"p22.png",id:"p22"},{src:"p23.png",id:"p23"},{src:"p24.png",id:"p24"},{src:"p25.png",id:"p25"},{src:"p26.png",id:"p26"},{src:"p27.png",id:"p27"},{src:"p28.png",
id:"p28"}]},!1);a.forQueue(queue);queue.load()}function onLoadComplete(a){qp_s()}
function qp_s(){qp_t();var a=new createjs.Shape;a.graphics.beginFill("#488451").drawRect(0,0,W,H);stage.addChild(a);var b=new createjs.Shape;b.graphics.beginFill("white").rect(0,200,W,H);a.hitArea=b;var c=0,d=0;a.on("mousedown",function(a){IS_TOUCH&&a.nativeEvent instanceof MouseEvent||qp_f||qp_p||(c=a.localY,d=stage.player.m[qp_d].y)});a.on("pressmove",function(a){IS_TOUCH&&a.nativeEvent instanceof MouseEvent||qp_f||qp_p||(stage.player.m[qp_d].visible=!0,stage.player.m[qp_d].y+=(a.localY-c)/5)});
a.on("pressup",function(a){IS_TOUCH&&a.nativeEvent instanceof MouseEvent||qp_f||qp_p||(50<c-a.localY?(stage.player.playAnimation(stage.player.m[qp_d]),qp_u((new Date).getTime()),createjs.Sound.play("count",!0)):(qp_v(d),stage.player.m[qp_d].visible=!1))});qp_a=[];for(a=0;a<=qp_c;a++)for(qp_a[a]=[],b=0;b<qp_b;b++){var e=new createjs.Bitmap(queue.getResult("d0"));e.regX=e.getBounds().width/2;e.regY=e.getBounds().height/2;e.x=genRandom(W);e.y=-H/2+genRandom(H);e.visible=!1;qp_a[a].push(e);stage.addChild(qp_a[a][b])}stage.player=
new Qp_w;stage.addChild(stage.player);a=new createjs.Shape;a.graphics.beginFill("black").rect(0,0,W,70);a.y=85;a.alpha=0.3;stage.addChild(a);stage.num=new createjs.Text("\uffe5"+qp_k.totalMoney,"bold 54px Arial","#ffab5f");stage.num.textAlign="center";stage.num.x=W/2;stage.num.y=95;stage.addChild(stage.num);stage.speed=new createjs.Text(qp_k.curSpeed,"bold 36px Arial","white");stage.speed.y=195;stage.speed.textAlign="center";stage.speed.x=W/2;stage.addChild(stage.speed);stage.bucketicon=new createjs.Bitmap(queue.getResult("bucket0"));
stage.bucketicon.x=-10;stage.bucketicon.y=600;stage.bucketicon.scaleX=0.3;stage.bucketicon.scaleY=0.3;stage.bucketicon.on("mousedown",function(a){IS_TOUCH&&a.nativeEvent instanceof MouseEvent||(qp_p=!0,createjs.Tween.get(stage.bucket).to({x:0},700),createjs.Ticker.addEventListener("tick",stage.bucket.coinAnimation),qp_q=setInterval(function(){createjs.Sound.play("coin",!0)},400))});stage.addChild(stage.bucketicon);a=new createjs.Bitmap(queue.getResult("bar"));a.x=120;a.y=H/2+80;a.scaleX=0.8;stage.addChild(a);
stage.swipeSpeedLabel=new createjs.Text("\uffe5"+qp_k.swipeNum,"bold 48px Arial","black");stage.swipeSpeedLabel.textAlign="center";stage.swipeSpeedLabel.x=W/2;stage.swipeSpeedLabel.y=H/2+95;stage.addChild(stage.swipeSpeedLabel);qp_m=new createjs.Shape;qp_m.graphics.beginFill("#185b54").drawRect(0,0,W,800);qp_m.y=H;stage.addChild(qp_m);stage.menu=new Qp_x;stage.menu.y=H;stage.addChild(stage.menu);stage.menulayer=new Qp_y;stage.menulayer.y=H-100;stage.addChild(stage.menulayer);stage.bucket=new Qp_z;
stage.bucket.x=W;stage.addChild(stage.bucket);setInterval(qp_A,1E3);stage.nflayer=new Qp_B;stage.nflayer.visible=!1;stage.addChild(stage.nflayer);stage.collectLayer=new Qp_C;stage.collectLayer.visible=!1;stage.addChild(stage.collectLayer);var f=0;setInterval(function(){f=stage.player.qp_D(f);var a=qp_E(),b=a/qp_k.capacity,c=0,c=0.1>b?0:0.3>b?1:0.5>b?2:0.7>b?3:0.9>b?4:5;stage.bucketicon.image=queue.getResult("bucket"+c);qp_p&&(stage.bucket.volumnLabel.text="\uffe5"+parseInt(a),stage.bucket.capacityLabel.text=
"/\uffe5"+parseInt(qp_k.capacity),stage.bucket.curbucket.image=queue.getResult("bucket"+c))},1E3);setInterval(qp_F,1E4);createjs.Ticker.addEventListener("tick",function(a){qp_k.totalMoney+=a.delta/1E3*(qp_G(a.timeStamp)+qp_k.curSpeed);stage.num.text="\uffe5"+qp_H(qp_k.totalMoney);stage.speed.text="\uffe5"+qp_I(qp_G((new Date).getTime())+qp_k.curSpeed)+"/\u79d2"})}
function qp_J(a){for(var b=0;b<qp_o[qp_e].length;b++)if(a>qp_o[qp_e][b].y&&a<qp_o[qp_e][b].y+150){qp_i.y=qp_o[qp_e][b].y;qp_i.visible=!0;createjs.Tween.get(qp_i).to({},300).to({visible:!1},0).call(function(){qp_K(b)});break}}
function qp_K(a){var b=qp_L(qp_e,a,qp_k.investiments[qp_e][a]);if(qp_k.totalMoney>b){var c=qp_M(qp_e,a);qp_k.moneyUsed+=b;stage.menu.title.text="\u603b\u8d44\u4ea7: "+qp_I(qp_k.moneyUsed);score=parseInt(qp_k.moneyUsed/1E4);gjQipa.newscore_wxoauth(score);qp_k.totalMoney-=b;qp_k.investiments[qp_e][a]++;qp_o[qp_e][a].txtItem[1].text=qp_k.investiments[qp_e][a];qp_o[qp_e][a].txtItem[2].text="\uffe5"+qp_I(qp_L(qp_e,a,qp_k.investiments[qp_e][a]));0==qp_e?qp_k.curSpeed+=c:1==qp_e?(qp_k.swipeNum+=c,stage.swipeSpeedLabel.text=
"\uffe5"+qp_k.swipeNum):2==qp_e&&(qp_k.lastBucketItemClickedTime=(new Date).getTime(),qp_k.totalMoney+=qp_E(),0==a%2?qp_k.offlineSpeed+=c:qp_k.capacity+=c)}else stage.nflayer.visible=!0,stage.nflayer.showAnimation()}function qp_N(a){if(-1E3==qp_j)qp_j=a;else{var b=a-qp_j;qp_j=a;for(a=0;a<qp_o[qp_e].length;a++)qp_o[qp_e][a].y+=b,qp_o[qp_e][a].visible=0<=qp_o[qp_e][a].y?!0:!1}}
function qp_O(){var a;150<qp_o[qp_e][0].y?(a=150-qp_o[qp_e][0].y,qp_P(a,1)):427>qp_o[qp_e][qp_o[qp_e].length-1].y&&(a=427-qp_o[qp_e][qp_o[qp_e].length-1].y,qp_P(a,2))}function qp_t(){if("yes1"==gjStorage.get("sign")){for(var a="",b=0;5>=b;b++)a+=gjStorage.get("moneyrain:mydata"+b);qp_k=JSON.parse(a)}else qp_k=new Qp_Q}
function qp_F(){qp_k.lastOnlineTime=(new Date).getTime();for(var a=JSON.stringify(qp_k,null,2),b=parseInt(a.length/5),c=0;5>=c;c++)gjStorage.set("moneyrain:mydata"+c,a.substr(b*c,b));gjStorage.set("sign","yes1")}
function Qp_R(a,b,c){this.initialize();this.name=qp_S[b][c][0];line=new createjs.Shape;line.graphics.setStrokeStyle(5,"round").beginStroke("#207073").moveTo(0,0).lineTo(W,0);this.addChild(line);this.bg=new createjs.Shape;this.bg.graphics.beginFill("#185b54").rect(0,0,W,180);this.addChild(this.bg);a=new createjs.Bitmap(queue.getResult(a));a.x=0;a.y=20;this.addChild(a);this.txtItem=[];var d=[];a=[[30,125],[200,75],[350,75],[W-30,75]];d.push(this.name);d.push(qp_k.investiments[b][c]);d.push("\uffe5"+
qp_I(qp_L(b,c,qp_k.investiments[b][c])));2==b?c%2?d.push("\uffe5"+qp_I(qp_M(b,c))+" \u5bb9\u91cf"):d.push("\uffe5"+qp_I(qp_M(b,c))+" /\u5c0f\u65f6"):d.push("\uffe5"+qp_I(qp_M(b,c)));for(b=0;b<d.length;b++)this.txtItem[b]=new createjs.Text(d[b],"bold 22px Arial","white"),this.txtItem[b].textAlign=0==b?"left":3==b?"right":"center",this.txtItem[b].x=a[b][0],this.txtItem[b].y=a[b][1],this.addChild(this.txtItem[b])}Qp_R.prototype=new createjs.Container;
function Qp_w(){this.initialize();this.mb=new createjs.Bitmap(queue.getResult("mb0"));this.mb.scaleX=0.8;this.mb.scaleY=0.8;this.mb.regX=this.mb.getBounds().width/2;this.mb.regY=this.mb.getBounds().height/2;this.mb.y=qp_g;this.x=W/2;this.y=H/2-150;this.addChild(this.mb);this.m=[];for(var a=0;3>=a;a++)this.m[a]=new createjs.Bitmap(queue.getResult("m0")),this.m[a].scaleX=0.8,this.m[a].scaleY=0.8,this.m[a].regX=this.m[a].getBounds().width/2,this.m[a].regY=this.m[a].getBounds().height/2,this.m[a].y=qp_g,
this.m[a].visible=!1,this.addChild(this.m[a])}Qp_w.prototype=new createjs.Container;Qp_w.prototype.qp_D=function(a){for(var b=(new Date).getTime(),c=1,d=0;d<qp_l.length;d++)b<qp_l[d]+1E3&&c++;c=parseInt(c/2);if(a==c)return a;if(!(3<c)){a=c;this.mb.image=queue.getResult("mb"+a);for(d=0;d<=qp_c;d++)this.m[d].image=queue.getResult("m"+a);for(d=0;d<qp_a.length;d++)for(b=0;b<qp_a[d].length;b++)qp_a[d][b].image=queue.getResult("d"+a);return a}};
Qp_w.prototype.playAnimation=function(a){a.visible=!0;createjs.Tween.get(a).to({scaleX:0.5,scaleY:0.5,y:-H},300).to({visible:!1,y:qp_g,scaleX:0.8,scaleY:0.8},0);0<qp_d?qp_d--:qp_d=qp_c};
function Qp_y(){this.initialize();this.descbg=new createjs.Shape;this.descbg.graphics.beginFill("#cc3844").rect(0,-50,W,50);this.descbg.visible=!1;this.addChild(this.descbg);this.desc=new createjs.Text(qp_T[qp_e][0]+" : "+qp_T[qp_e][1],"bold 20px Arial","white");this.desc.textAlign="center";this.desc.x=W/2;this.desc.y=-40;this.desc.visible=!1;this.addChild(this.desc);qp_r=[];for(var a=0;3>a;a++)qp_r[a]=new createjs.Shape,qp_r[a].graphics.beginFill("white").rect(W/3*a,0,W/3,100),qp_r[a].alpha=0.7,
this.addChild(qp_r[a]);a=new createjs.Shape;a.graphics.beginFill("white").rect(-50,0,W/3,100);this.bt1=new createjs.Bitmap(queue.getResult("bt2"));this.bt1.regX=this.bt1.getBounds().width/2;this.bt1.x=W/6;this.bt1.hitArea=a;this.bt1.on("mousedown",function(a){IS_TOUCH&&a.nativeEvent instanceof MouseEvent||qp_n||qp_p||qp_U(0)});this.addChild(this.bt1);this.bt2=new createjs.Bitmap(queue.getResult("bt3"));this.bt2.regX=this.bt2.getBounds().width/2;this.bt2.x=W/2;this.bt2.hitArea=a;this.bt2.on("mousedown",
function(a){IS_TOUCH&&a.nativeEvent instanceof MouseEvent||qp_n||qp_p||qp_U(1)});this.addChild(this.bt2);this.bt3=new createjs.Bitmap(queue.getResult("bt1"));this.bt3.regX=this.bt3.getBounds().width/2;this.bt3.x=5*W/6;this.bt3.hitArea=a;this.bt3.on("mousedown",function(a){IS_TOUCH&&a.nativeEvent instanceof MouseEvent||qp_n||qp_p||qp_U(2)});this.addChild(this.bt3)}Qp_y.prototype=new createjs.Container;
function Qp_z(){this.initialize();this.bg=new createjs.Shape;this.bg.graphics.beginFill("black").rect(0,0,W,H);this.bg.alpha=0.5;this.addChild(this.bg);this.close=new createjs.Bitmap(queue.getResult("close"));this.close.x=550;this.close.on("mousedown",function(a){IS_TOUCH&&a.nativeEvent instanceof MouseEvent||(createjs.Tween.get(stage.bucket).to({x:W},700),qp_p=!1,createjs.Ticker.removeEventListener("tick",stage.bucket.coinAnimation),window.clearInterval(qp_q))});this.addChild(this.close);qp_h=[];
for(var a=0;5>a;a++)qp_h[a]=new createjs.Bitmap(queue.getResult("coin")),qp_h[a].rotation=genRandom(41)-20,qp_h[a].y=qp_g+90*a-300,qp_h[a].x=W/2-50+genRandom(100),this.addChild(qp_h[a]);a=H/6;this.curbucket=new createjs.Bitmap(queue.getResult("bucket0"));this.curbucket.x=0;this.curbucket.y=a-100;this.addChild(this.curbucket);this.volumnLabel=new createjs.Text("200K","bold 20px Arial","black");this.volumnLabel.y=H/2+150;this.volumnLabel.x=W/2-30;this.addChild(this.volumnLabel);this.capacityLabel=new createjs.Text("200K",
"bold 20px Arial","black");this.capacityLabel.y=H/2+180;this.capacityLabel.x=W/2-30;this.addChild(this.capacityLabel);var b=new createjs.Bitmap(queue.getResult("btCollect"));b.x=60;b.y=a+700;b.scaleX=0.7;b.scaleY=0.7;b.on("mousedown",function(a){IS_TOUCH&&a.nativeEvent instanceof MouseEvent||(qp_k.totalMoney+=qp_E(),qp_k.lastBucketItemClickedTime=(new Date).getTime(),stage.collectLayer.visible=!0,stage.collectLayer.showAnimation())});this.addChild(b);b=new createjs.Text("\u6536\u94b1","bold 20px Arial",
"black");b.x=105;b.y=a+725;this.addChild(b);b=new createjs.Bitmap(queue.getResult("btCollect"));b.x=460;b.y=a+700;b.scaleX=0.7;b.scaleY=0.7;b.on("mousedown",function(a){IS_TOUCH&&a.nativeEvent instanceof MouseEvent||(qp_p=!1,window.clearInterval(qp_q),createjs.Tween.get(stage.bucket).to({x:W},50).call(function(){qp_U(2);createjs.Ticker.removeEventListener("tick",stage.bucket.coinAnimation)}))});this.addChild(b);b=new createjs.Text("\u6269\u5bb9","bold 20px Arial","black");b.x=505;b.y=a+725;this.addChild(b)}
Qp_z.prototype=new createjs.Container;Qp_z.prototype.coinAnimation=function(){for(var a,b=0;b<qp_h.length;b++){a=qp_h[b];var c=Math.sqrt(12*(qp_h[b].y+15));680<a.y+c?(a.y=qp_g-300,a.x=W/2-50+genRandom(100),a.rotation=genRandom(41)-20):a.y+=c}};
function Qp_x(){this.initialize();var a;qp_o=[];for(a=0;a<qp_S.length;a++){qp_o[a]=[];for(var b=0;b<qp_S[a].length;b++)0==a?qp_o[a][b]=new Qp_R("p"+a+""+(b+1),a,b):1==a?qp_o[a][b]=new Qp_R("p"+a+""+(b+1),a,b):2==a&&(qp_o[a][b]=new Qp_R("p"+a+""+(b+1),a,b)),qp_o[a][b].y=181*b+150,qp_e!=a&&(qp_o[a][b].visible=!1),this.addChild(qp_o[a][b])}qp_i=new createjs.Shape;qp_i.graphics.beginFill("black").rect(0,0,W,180);qp_i.alpha=0.3;qp_i.visible=!1;this.addChild(qp_i);this.bg=new createjs.Shape;this.bg.graphics.beginFill("#cc3844").rect(0,
0,W,150);b=new createjs.Shape;b.graphics.beginFill("white").rect(0,0,W,H/5*4+50);this.bg.hitArea=b;var c,d,e;this.bg.on("mousedown",function(a){IS_TOUCH&&a.nativeEvent instanceof MouseEvent||(d=a.timeStamp,c=a.localY)});this.bg.on("pressmove",function(a){IS_TOUCH&&a.nativeEvent instanceof MouseEvent||loadFinish&&qp_N(a.localY)});this.bg.on("pressup",function(a){if(!(IS_TOUCH&&a.nativeEvent instanceof MouseEvent)){qp_j=-1E3;e=(new Date).getTime();pressupY=a.localY;a=e-d;var b=pressupY-c;3>Math.abs(b)&&
qp_J(pressupY);qp_V(b,a)}});this.addChild(this.bg);this.title=new createjs.Text("\u603b\u8d44\u4ea7: "+qp_I(qp_k.moneyUsed),"bold 22px Arial","white");this.title.x=W/2;this.title.textAlign="center";this.title.y=40;this.addChild(this.title);for(var f=["\u9879\u76ee","\u7ea7\u522b","\u82b1\u8d39","\u6536\u76ca"],g=[30,180,350,W-30],b=0;b<f.length;b++)a=new createjs.Text(f[b],"bold 22px Arial","white"),a.textAlign=0==b?"left":3==b?"right":"center",a.x=g[b],a.y=110,this.addChild(a);a=new createjs.Bitmap(queue.getResult("share"));
a.x=10;a.y=10;a.on("click",function(a){score>best&&(best=score);share()});this.addChild(a);b=new createjs.Bitmap(queue.getResult("close"));b.x=560;b.y=10;b.scaleX=0.9;b.scaleY=0.9;b.on("mousedown",function(a){IS_TOUCH&&a.nativeEvent instanceof MouseEvent||qp_U(qp_e)});this.addChild(b)}Qp_x.prototype=new createjs.Container;
function Qp_B(){this.initialize();var a=new createjs.Shape;a.graphics.beginFill("black").rect(0,0,W,H);a.alpha=0.3;this.addChild(a);this.txt=new createjs.Text("\u53ef\u7528\u4f59\u989d\u4e0d\u8db3!","bold 42px Arial","green");this.txt.y=H/2;this.txt.x=W;this.addChild(this.txt)}Qp_B.prototype=new createjs.Container;Qp_B.prototype.showAnimation=function(){this.txt.x=W;createjs.Tween.get(this.txt).to({x:440},400).to({x:100},800).to({x:-200},400).call(function(){stage.nflayer.visible=!1})};
function Qp_C(){this.initialize();var a=new createjs.Shape;a.graphics.beginFill("black").rect(0,0,W,H);a.alpha=0.3;this.addChild(a);this.txt=new createjs.Text("\u6536\u94b1\u6210\u529f!","bold 42px Arial","green");this.txt.y=H/2;this.txt.x=W;this.addChild(this.txt)}Qp_C.prototype=new createjs.Container;Qp_C.prototype.showAnimation=function(){this.txt.x=W;createjs.Tween.get(this.txt).to({x:440},400).to({x:100},800).to({x:-200},400).call(function(){stage.collectLayer.visible=!1})};
function Qp_Q(){this.lastBucketItemClickedTime=(new Date).getTime();this.swipeNum=this.curSpeed=1;this.totalMoney=100;this.offlineSpeed=this.capacity=30;this.moneyUsed=0;this.investiments=[];for(var a=0;a<qp_S.length;a++){this.investiments[a]=[];for(var b=0;b<qp_S[a].length;b++)this.investiments[a][b]=0}}function genRandom(a){return parseInt(Math.random()*a)}
function qp_H(a){var b=a.toExponential(16).toString(),c=parseInt(b.substr(b.search("e")+1,b.length)),d=0;16<c&&(a=parseFloat(b.substr(0,b.search("e"))),d=parseInt((c-16)/4)+1,c-=4*d+qp_W[d].length,a*=Math.pow(10,c+1));c=parseInt(a).toString();a=0;for(var b="",e=c.length-1;0<=e;e--)4==a?(e++,b+=" ",a=0):(b+=c[e],a++);return b.split("").reverse().join("")+qp_W[d]}function qp_X(a,b,c){if(1<=c&&3>=c)return qp_S[a][b][2*c-1]*Math.pow(10,qp_Y[qp_S[a][b][2*c]]);alert("Illegal use with qp_X!")}
function qp_I(a){a=a.toExponential(2).toString();var b,c="",c=0;b=a.substr(0,a.search("e"));c=parseInt(a.substr(a.search("e")+1,a.length));0>c?(b*=Math.pow(10,c),c=1):b*=Math.pow(10,c%4);c=qp_W[parseInt(c/4)];return b.toFixed(1)+" "+c}function qp_u(a){if(0!=qp_l.length){var b;for(b=0;b<qp_l.length&&!(qp_l[b]>a-1E3);b++);for(var c=b;c<qp_l.length;c++)qp_l[c-b]=qp_l[c];qp_l.length-=b}qp_l.push(a)}
function qp_G(a){for(var b=0,b=0;b<qp_l.length&&!(qp_l[b]>a-1E3);b++);a=qp_l.length-b;return qp_k.swipeNum*a*([1,1.5,2,2.5][parseInt(a/2.3)]||2.5)}function qp_U(a){qp_f?qp_e==a?(qp_ba(!1),qp_bb(!1),qp_f=!1):(qp_e=a,qp_bb(!0),qp_Z(qp_e)):(qp_e!=a&&(qp_Z(a),qp_e=a),qp_ba(!0),qp_bb(!0),qp_f=!0)}
function qp_Z(a){for(var b=0;3>b;b++)if(a==b)for(var c=0;c<qp_o[b].length;c++)qp_o[b][c].visible=0<=qp_o[b][c].y?!0:!1;else for(c=0;c<qp_o[b].length;c++)qp_o[b][c].visible=!1;stage.menulayer.desc.text=qp_T[a][0]+" : "+qp_T[a][1]}function qp_D(a){0<=a&&5>=a?a!=curBucketImage&&(curBucketImage=a,stage.bucket.curbucket.image=queue.getResult("bucket"+a)):console.log("Invalid use of qp_D")}
function qp_E(){var a=((new Date).getTime()-qp_k.lastBucketItemClickedTime)/1E3*qp_k.offlineSpeed/3600;return a<qp_k.capacity?a:qp_k.capacity}function qp_bb(a){if(a)for(a=0;a<qp_r.length;a++)qp_r[a].alpha=1,qp_e==a?qp_r[a].graphics.clear().beginFill("#cc3844").rect(a*W/3,0,W/3,100):qp_r[a].graphics.clear().beginFill("#a52b37").rect(a*W/3,0,W/3,100);else for(a=0;a<qp_r.length;a++)qp_r[a].graphics.clear().beginFill("white").rect(a*W/3,0,W/3,100),qp_r[a].alpha=0.2}
function qp_ba(a){qp_n=!0;a?(createjs.Tween.get(stage.menu).to({y:H/5+60},500).call(function(){loadFinish=!0;qp_n=!1;stage.menulayer.descbg.visible=!0;stage.menulayer.desc.visible=!0}),createjs.Tween.get(qp_m).to({y:H/5+60},500)):(stage.menulayer.descbg.visible=!1,loadFinish=stage.menulayer.desc.visible=!1,createjs.Tween.get(stage.menu).to({y:H},500).call(function(){qp_n=!1}),createjs.Tween.get(qp_m).to({y:H},500))}function qp_L(a,b,c){a=qp_X(a,b,1);return Math.pow(1.3,c)*a}
function qp_M(a,b){return qp_X(a,b,2)}
var qp_S=[[["\u9e21",1E3,"",5,""],["\u732a",15,"K",30,""],["\u7f8a",80,"K",160,""],["\u9c7c",400,"K",500,""],["\u725b",6500,"K",8E3,""],["\u9a6c",50,"M",250,"K"],["\u519c\u7530",5E3,"M",20,"M"],["\u5927\u519c\u573a",80,"B",100,"M"]],[["\u714e\u997c\u644a",1E3,"",2,""],["\u6742\u8d27\u94fa",17.5,"K",10,""],["\u8bca\u6240",350,"K",100,""],["\u5f71\u9662",7.5,"M",1,"K"],["\u4f53\u80b2\u9986",100,"M",10,"K"],["\u9ad8\u6863\u996d\u5e97",1400,"M",100,"K"],["\u8d2d\u7269\u4e2d\u5fc3",18.5,"B",1,"M"],["\u6469\u5929\u5927\u697c",
275,"B",10,"M"]],[["\u6d3b\u671f\u5b58\u6b3e",150,"K",300,"K"],["\u5b9a\u671f\u5b58\u6b3e",500,"K",1600,"K"],["\u4fe1\u6258\u7406\u8d22",4E3,"K",6E3,"K"],["\u8d27\u5e01\u57fa\u91d1",40,"M",12,"M"],["\u80a1\u7968\u57fa\u91d1",150,"M",36,"M"],["\u80a1\u5e02\u6295\u8d44",800,"M",560,"M"],["\u98ce\u9669\u6295\u8d44",36,"B",16,"B"],["\u5bf9\u51b2\u57fa\u91d1",200,"B",400,"B"]]],qp_T=[["\u519c\u4e1a","\u5728\u7ebf\u5373\u53ef\u6323\u94b1"],["\u751f\u610f","\u901a\u8fc7\u5212\u52a8\u949e\u7968\u6323\u94b1"],
["\u7406\u8d22","\u79bb\u7ebf\u4e5f\u53ef\u6323\u94b1"]],qp_Y={"":0,K:3,M:6,B:9,KB:12,MB:15,BB:18,KBB:21,MBB:24,BBB:27},qp_W=" \u4e07 \u4ebf \u4e07\u4ebf \u4ebf\u4ebf \u4e07\u4ebf\u4ebf \u4ebf\u4ebf\u4ebf \u4e07\u4ebf\u4ebf\u4ebf \u4ebf\u4ebf\u4ebf\u4ebf".split(" ");
function qp_V(a,b){b=100*a/b/3E3;a=1500*b*b;for(var c=0;c<qp_o[qp_e].length;c++)0<a?0==c?0<qp_o[qp_e][c].y+a?(dy2=qp_o[qp_e][c].y+a,0>qp_o[qp_e][c].y?(dy1=-1*qp_o[qp_e][c].y,createjs.Tween.get(qp_o[qp_e][c]).to({y:0},dy1/a*b).to({visible:!0},0).to({y:dy2},dy2/a*b).call(qp_O)):createjs.Tween.get(qp_o[qp_e][c]).to({y:dy2},b).call(qp_O)):createjs.Tween.get(qp_o[qp_e][c]).to({y:qp_o[qp_e][c].y+a},b).call(qp_O):0<qp_o[qp_e][c].y+a?(dy2=qp_o[qp_e][c].y+a,0>qp_o[qp_e][c].y?(dy1=-1*qp_o[qp_e][c].y,createjs.Tween.get(qp_o[qp_e][c]).to({y:0},
dy1/a*b).to({visible:!0},0).to({y:dy2},dy2/a*b)):createjs.Tween.get(qp_o[qp_e][c]).to({y:dy2},b)):createjs.Tween.get(qp_o[qp_e][c]).to({y:qp_o[qp_e][c].y+a},b):0==c?0>qp_o[qp_e][c].y+a?(dy2=qp_o[qp_e][c].y+a,0<qp_o[qp_e][c].y?(dy1=-1*qp_o[qp_e][c].y,createjs.Tween.get(qp_o[qp_e][c]).to({y:0},dy1/a*b).to({visible:!1},0).to({y:dy2},dy2/a*b).call(qp_O)):createjs.Tween.get(qp_o[qp_e][c]).to({y:dy2},b).call(qp_O)):createjs.Tween.get(qp_o[qp_e][c]).to({y:qp_o[qp_e][c].y+a},b).call(qp_O):0>qp_o[qp_e][c].y+
a?(dy2=qp_o[qp_e][c].y+a,0<qp_o[qp_e][c].y?(dy1=-1*qp_o[qp_e][c].y,createjs.Tween.get(qp_o[qp_e][c]).to({y:0},dy1/a*b).to({visible:!1},0).to({y:dy2},dy2/a*b)):createjs.Tween.get(qp_o[qp_e][c]).to({y:dy2},b)):createjs.Tween.get(qp_o[qp_e][c]).to({y:qp_o[qp_e][c].y+a},b)}
function qp_P(a,b){for(var c,d,e=0;e<qp_o[qp_e].length;e++)1==b?createjs.Tween.get(qp_o[qp_e][e]).to({y:qp_o[qp_e][e].y+a},300):2==b&&(0<qp_o[qp_e][e].y+a?(d=qp_o[qp_e][e].y+a,0>qp_o[qp_e][e].y?(c=-1*qp_o[qp_e][e].y,createjs.Tween.get(qp_o[qp_e][e]).to({y:0},c/a*300).to({visible:!0},0).to({y:d},d/a*300)):createjs.Tween.get(qp_o[qp_e][e]).to({y:d},300)):createjs.Tween.get(qp_o[qp_e][e]).to({y:qp_o[qp_e][e].y+a},300))}var qp_bc=0;
function qp_A(){for(var a=0;a<qp_b;a++)qp_a[qp_bc][a].visible=!0,createjs.Tween.get(qp_a[qp_bc][a]).to({y:H+qp_a[qp_bc][a].getBounds().height/2+100,rotation:720+genRandom(400),x:genRandom(W)},1E3+genRandom(800)).to({visible:!1},10).to({x:genRandom(W),y:-H/2+genRandom(H/2),rotation:0},10);qp_bc<qp_c?qp_bc++:qp_bc=0}function qp_v(a){createjs.Tween.get(stage.player.m[qp_d]).to({y:a},200)};
